-- Script generated by Redgate Compare v1.19.6.13016
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.fc_lista_dfe(bigint)...';END$$;
CREATE FUNCTION public.fc_lista_dfe(IN pid_dfe bigint)
RETURNS TABLE(id_dfe bigint, mensagem character varying, chave character varying, datahora timestamp without time zone)
LANGUAGE sql
AS $_$
select id, mensagem, chave, datahora
from tbl_dfe 
where id = pid_dfe
$_$;
ALTER FUNCTION public.fc_lista_dfe(IN pid_dfe bigint) OWNER TO systaxdfe;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.fc_ins_dfe(character varying, character varying)...';END$$;
CREATE FUNCTION public.fc_ins_dfe(IN p_mensagem character varying, IN p_chave character varying)
RETURNS void
LANGUAGE sql
AS $_$
	insert into tbl_dfe(mensagem, chave) values (p_mensagem, p_chave);
$_$;
ALTER FUNCTION public.fc_ins_dfe(IN p_mensagem character varying, IN p_chave character varying) OWNER TO systaxdfe;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.fc_ins_dfe(character varying)...';END$$;
CREATE FUNCTION public.fc_ins_dfe(IN p_mensagem character varying)
RETURNS void
LANGUAGE sql
AS $_$
	insert into tbl_dfe(mensagem) values (p_mensagem);
$_$;
ALTER FUNCTION public.fc_ins_dfe(IN p_mensagem character varying) OWNER TO systaxdfe;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.tbl_usuarios_id_seq...';END$$;
CREATE SEQUENCE public.tbl_usuarios_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
ALTER SEQUENCE public.tbl_usuarios_id_seq OWNER TO systaxdfe;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.tbl_usuarios...';END$$;
CREATE TABLE public.tbl_usuarios (
    id integer NOT NULL DEFAULT nextval('public.tbl_usuarios_id_seq'::regclass),
    nome character varying(100),
    status integer
);
ALTER TABLE public.tbl_usuarios OWNER TO systaxdfe;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.tbl_usuarios_id_seq...';END$$;
ALTER SEQUENCE public.tbl_usuarios_id_seq OWNED BY public.tbl_usuarios.id;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.tbl_prod01_id_seq...';END$$;
CREATE SEQUENCE public.tbl_prod01_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
ALTER SEQUENCE public.tbl_prod01_id_seq OWNER TO systaxdfe;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.tbl_prod01...';END$$;
CREATE TABLE public.tbl_prod01 (
    id integer NOT NULL DEFAULT nextval('public.tbl_prod01_id_seq'::regclass),
    nome character varying(100)
);
ALTER TABLE public.tbl_prod01 OWNER TO systaxdfe;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.tbl_prod01_id_seq...';END$$;
ALTER SEQUENCE public.tbl_prod01_id_seq OWNED BY public.tbl_prod01.id;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.tbl_dfe_id_seq...';END$$;
CREATE SEQUENCE public.tbl_dfe_id_seq
AS bigint
INCREMENT BY 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1
CACHE 1
NO CYCLE;
ALTER SEQUENCE public.tbl_dfe_id_seq OWNER TO systaxdfe;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.tbl_dfe...';END$$;
CREATE TABLE public.tbl_dfe (
    id bigint NOT NULL DEFAULT nextval('public.tbl_dfe_id_seq'::regclass),
    mensagem character varying(100),
    datahora timestamp without time zone NOT NULL DEFAULT now(),
    chave character varying(36)
);
ALTER TABLE public.tbl_dfe OWNER TO systaxdfe;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.tbl_dfe_id_seq...';END$$;
ALTER SEQUENCE public.tbl_dfe_id_seq OWNED BY public.tbl_dfe.id;

SET check_function_bodies = true;
