-- Script generated by Redgate Compare v1.19.6.13016
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.tbl_homolog01_id_seq...';END$$;
ALTER SEQUENCE public.tbl_homolog01_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.tbl_homolog01...';END$$;
DROP TABLE public.tbl_homolog01;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.tbl_homolog01_id_seq...';END$$;
DROP SEQUENCE public.tbl_homolog01_id_seq;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.tbl_prod01_id_seq...';END$$;
CREATE SEQUENCE public.tbl_prod01_id_seq
AS integer
INCREMENT BY 1
MINVALUE 1
MAXVALUE 2147483647
START 1
CACHE 1
NO CYCLE;
ALTER SEQUENCE public.tbl_prod01_id_seq OWNER TO systaxdfe;


DO language plpgsql $$BEGIN RAISE NOTICE 'Creating public.tbl_prod01...';END$$;
CREATE TABLE public.tbl_prod01 (
    id integer NOT NULL DEFAULT nextval('public.tbl_prod01_id_seq'::regclass),
    nome character varying(100)
);
ALTER TABLE public.tbl_prod01 OWNER TO systaxdfe;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.tbl_prod01_id_seq...';END$$;
ALTER SEQUENCE public.tbl_prod01_id_seq OWNED BY public.tbl_prod01.id;

SET check_function_bodies = true;
