-- Script generated by Redgate Compare v1.19.6.13016
SET check_function_bodies = false;


DO language plpgsql $$BEGIN RAISE NOTICE 'Altering public.tbl_homolog03_id_seq...';END$$;
ALTER SEQUENCE public.tbl_homolog03_id_seq OWNED BY NONE;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.tbl_homolog03...';END$$;
DROP TABLE public.tbl_homolog03;


DO language plpgsql $$BEGIN RAISE NOTICE 'Dropping public.tbl_homolog03_id_seq...';END$$;
DROP SEQUENCE public.tbl_homolog03_id_seq;

SET check_function_bodies = true;
